<?php
// Styles loaded from manage-registry.css via page_styles in layout.php
// JavaScript loaded from permission-manager.js and manage-registry.js via page_script
?>

    <!-- About Section -->
    <div class="card mb-4 border-info">
      <div class="card-header bg-info bg-opacity-10" style="cursor: pointer;" data-bs-toggle="collapse" data-bs-target="#aboutFunctionRegistries">
        <h5 class="mb-0"><i class="fa fa-info-circle"></i> About Function Registries <i class="fa fa-chevron-down float-end"></i></h5>
      </div>
      <div class="collapse" id="aboutFunctionRegistries">
        <div class="card-body">
          <p><strong>Purpose:</strong> Auto-generate searchable registries of all PHP and JavaScript functions in your codebase.</p>
          
          <p><strong>Why This Matters:</strong> The registries help developers quickly find functions they need. They're generated automatically from function definitions and docblocks in your code. This page lets you:</p>
          <ul>
            <li>Trigger a full registry scan and update</li>
            <li>View when registries were last updated</li>
            <li>See registry files being used (HTML and Markdown formats)</li>
            <li>Check for permission issues preventing updates</li>
          </ul>
          
          <p><strong>How It Works:</strong></p>
          <ul>
            <li>PHP registry is generated by scanning lib/*.php files</li>
            <li>JavaScript registry is generated by scanning js/*.js files</li>
            <li>Both produce HTML (for web browsing) and Markdown (for documentation)</li>
            <li>Registry updates happen via command-line PHP scripts</li>
          </ul>
          
          <p class="mb-0"><strong>What You Can Do:</strong></p>
          <ul class="mb-0">
            <li>Generate/regenerate the PHP function registry</li>
            <li>Generate/regenerate the JavaScript function registry</li>
            <li>View timestamps of last successful updates</li>
            <li>Check which registry files exist and are accessible</li>
            <li>See errors if registry generation fails</li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Permission Alerts for Registry Files -->
    <?php echo generatePermissionAlert(
        $php_registry_html,
        'PHP Registry HTML File',
        'Web server cannot write to function_registry.html.',
        'file'
    ); ?>
    
    <?php echo generatePermissionAlert(
        $php_registry_md,
        'PHP Registry Markdown File',
        'Web server cannot write to FUNCTION_REGISTRY.md.',
        'file'
    ); ?>
    
    <?php echo generatePermissionAlert(
        $js_registry_html,
        'JavaScript Registry HTML File',
        'Web server cannot write to js_function_registry.html.',
        'file'
    ); ?>
    
    <?php echo generatePermissionAlert(
        $js_registry_md,
        'JavaScript Registry Markdown File',
        'Web server cannot write to JS_FUNCTION_REGISTRY.md.',
        'file'
    ); ?>

    <!-- PHP Registry Card -->
    <div class="card mb-4">
      <div class="card-header bg-primary text-white">
        <h5 class="mb-0"><i class="fa fa-code"></i> PHP Function Registry</h5>
      </div>
      <div class="card-body">
        <p class="mb-3">
          Auto-generated searchable index of all PHP functions with documentation, usage tracking, and duplicate detection.
        </p>
        <div class="mb-3">
          <button class="btn btn-primary btn-sm w-100 mb-2" onclick="location.href='../docs/function_registry.html'" target="_blank">
            <i class="fa fa-external-link"></i> View HTML
          </button>
          <button class="btn btn-info btn-sm w-100 mb-2" onclick="location.href='../docs/FUNCTION_REGISTRY.md'" target="_blank">
            <i class="fa fa-file-text"></i> View Markdown
          </button>
          <button class="btn btn-warning btn-sm w-100" onclick="updateRegistry('php')">
            <i class="fa fa-refresh"></i> Update Now
          </button>
        </div>
        <div class="text-muted small">
          <i class="fa fa-clock-o"></i> Last updated: <strong><?php echo $php_last_update; ?></strong>
        </div>
        <div id="phpResult" class="mt-3 d-none"></div>
      </div>
    </div>

    <!-- JavaScript Registry Card -->
    <div class="card mb-4">
      <div class="card-header bg-info text-white">
        <h5 class="mb-0"><i class="fa fa-code"></i> JavaScript Function Registry</h5>
      </div>
      <div class="card-body">
        <p class="mb-3">
          Auto-generated searchable index of all JavaScript functions with documentation and usage tracking.
        </p>
        <div class="mb-3">
          <button class="btn btn-info btn-sm w-100 mb-2" onclick="location.href='../docs/js_function_registry.html'" target="_blank">
            <i class="fa fa-external-link"></i> View HTML
          </button>
          <button class="btn btn-info btn-sm w-100 mb-2" onclick="location.href='../docs/JS_FUNCTION_REGISTRY.md'" target="_blank">
            <i class="fa fa-file-text"></i> View Markdown
          </button>
          <button class="btn btn-warning btn-sm w-100" onclick="updateRegistry('js')">
            <i class="fa fa-refresh"></i> Update Now
          </button>
        </div>
        <div class="text-muted small">
          <i class="fa fa-clock-o"></i> Last updated: <strong><?php echo $js_last_update; ?></strong>
        </div>
        <div id="jsResult" class="mt-3 d-none"></div>
      </div>
    </div>

    <!-- Info Section -->
    <div class="alert alert-info">
      <h6 class="alert-heading"><i class="fa fa-lightbulb"></i> How to Use</h6>
      <p class="mb-2">
        The registry generators automatically scan your code files and create searchable indexes with:
      </p>
      <ul class="mb-2">
        <li><strong>PHP Registry:</strong> All functions from <code>lib/</code>, <code>tools/</code>, and <code>admin/</code> directories</li>
        <li><strong>JavaScript Registry:</strong> All functions from <code>js/</code> directory</li>
      </ul>
      <p class="mb-2">
        <strong>Update When:</strong> After adding new functions, modifying existing functions, or moving functions between files.
      </p>
      <p class="mb-0">
        <strong>Permissions:</strong> If you get permission errors when updating, click the <strong>Permissions Help</strong> button for instructions.
      </p>
    </div>
