<?php
/**
 * APPLICATION CONFIGURATION - DEFAULT VALUES
 * 
 * This file defines DEFAULT site-wide settings and paths.
 * These values can be overridden by config/config_editable.json (which contains current values).
 * 
 * Configuration is loaded by ConfigManager in this order:
 * 1. Load defaults from site_config.php (this file)
 * 2. Merge overrides from config_editable.json (if it exists)
 * 3. Result is the active configuration
 * 
 * ⚠️  IMPORTANT FOR NEW ADMINS:
 * - DO NOT edit this file to change settings
 * - Use the Admin Dashboard -> "Manage Site Configuration" instead
 * - That tool updates config_editable.json with the current values
 * - Editable settings: siteTitle, admin_email, sequence_types
 * - Structural settings (paths, site, root_path) are NOT editable for safety
 * 
 * For multi-site deployments:
 * - 'site' is the directory name (e.g., 'moop', 'easy_gdb') 
 * - CHANGE THIS to deploy for a different site directory
 * - Derived paths are calculated automatically from root_path + site
 * - All absolute paths use root_path as base
 * - All URLs use /site as the web root (e.g., /moop/images, /easy_gdb/images)
 */

// Calculate derived paths from root_path and site (no need to edit these)
$root_path = '/var/www/html';
$site = 'moop';  // CHANGE THIS to deploy for a different site directory
$site_path = "$root_path/$site";
$images_dir = 'images';

return [
    // ======== REQUIRED: Server Paths ========
    // These must exist on your server, or the app won't function
    // These are STRUCTURAL and cannot be edited through the admin interface
    'root_path' => $root_path,
    'site' => $site,
    'site_path' => $site_path,
    'organism_data' => "$site_path/organisms",
    
    // ======== REQUIRED: Directory Names ========
    'images_dir' => $images_dir,
    'images_path' => "$site/$images_dir",  // Web path for <img src>
    'absolute_images_path' => "$site_path/$images_dir",  // Filesystem path
    
    // ======== REQUIRED: Metadata ========
    'metadata_path' => "$site_path/metadata",
    
    // ======== REQUIRED: Documentation ========
    'docs_path' => "$site_path/docs",
    
    // ======== OPTIONAL: Appearance ========
    // EDITABLE in Admin Dashboard: Use "Manage Site Configuration" to change these
    'siteTitle' => 'SIMRbase',  // Changed in config_editable.json if customized
    'header_img' => 'header_img.png',
    'banners_path' => "$site_path/images/banners",
    'favicon_path' => "/$site/$images_dir/favicon.ico",
    'custom_css_path' => "$site_path/css/custom.css",
    
    // ======== OPTIONAL: Contact ========
    // EDITABLE in Admin Dashboard: Use "Manage Site Configuration" to change these
    'admin_email' => 'admin@example.com',  // Changed in config_editable.json if customized
    
    // ======== OPTIONAL: Files ========
    'users_file' => "$root_path/users.json",
    
    // ======== OPTIONAL: IP-Based Auto-Login ========
    // IP ranges for automatic login with full access (development/local testing)
    // Format: Array of ranges with 'start' and 'end' IP addresses
    // Leave empty array to disable IP-based auto-login
    // Example: ['127.0.0.0', '127.0.0.255'] for localhost range
    'auto_login_ip_ranges' => [
        [
            'start' => '127.0.0.11',
            'end' => '127.0.0.11',
        ],
    ],
    
    // ======== DATA CONFIGURATION ========
    // DEFAULT sequence file types and display labels
    // EDITABLE in Admin Dashboard: Use "Manage Site Configuration" to:
    //   - Enable/disable sequence types for users
    //   - Customize display labels (e.g., "Transcript" instead of "mRNA")
    // File patterns are read-only (tied to actual filenames in organism directories)
    // Current values come from config_editable.json if customized, otherwise defaults below
    'sequence_types' => [
        'protein' => [
            'pattern' => 'protein.aa.fa',
            'label' => 'Protein',
        ],
        'transcript' => [
            'pattern' => 'transcript.nt.fa',
            'label' => 'mRNA',
        ],
        'cds' => [
            'pattern' => 'cds.nt.fa',
            'label' => 'CDS',
        ],
        'genome' => [
            'pattern' => 'genome.fa',
            'label' => 'GENOME',
        ]
    ],
    
    // ======== BLAST TOOL SAMPLE SEQUENCES ========
    // Sample sequences for users to test BLAST functionality
    'blast_sample_sequences' => [
        'protein' => '>tr|A0A7N2L231|A0A7N2L231_QUELO Histone H4 OS=Quercus lobata OX=97700 GN=LOC115987528 PE=3 SV=1
MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLK
IFLENVIRDAVTYTEHARRKTVTAMDVVYALKRQGRTLYGFGG',
        'nucleotide' => '>ENSRNOT00000066367.5 H2ac25-201 cdna:protein_coding
GCTCAGTCTAGCCTCCCTCCTGATCATATATAAGAGCTTGCTGGCGCTTACAGATTCGTT
TTTTGCCAGCTTTCTTCTGTTTCTGTACTTTTGGTCGTTAGGGGAAGATGTCTGGTCGTG
GCAAGCAGGGCGGCAAAGCTCGTGCAAAAGCGAAGTCTCGCTCATCCCGCGCTGGCCTGC
AGTTTCCAGTGGGCCGTGTGCACCGCCTTCTCCGTAAGGGCAACTACTCGGAGCGGGTGG
GCGCCGGCGCTCCGGTGTACCTAGCGGCTGTGCTGGAATACCTGACTGCTGAGATCCTGG
AGCTGGCTGGGAATGCGGCCCGCGATAATAAGAAGACGCGGATTATCCCGCGCCACCTGC
AGTTGGCCATCCGCAACGACGAGGAGCTCAACAAGCTGCTGGGCCGCGTGACCATCGCGC
AGGGCGGCGTCCTGCCCAACATCCAGGCGGTGTTGCTGCCCAAGAAGACGGAGAGCCACC
ACAAGGCCAAGGGCAAGTGAGGCCCTGCTGGTCGTTAGAGCAACTTTACGGACACCAAAG
GCTCTTTTCAGAGCCACCCCCAACCTCATTAGGAAGTGCTGTACACTGAGCCTGTCGCCA
GTTACTGGCCGGCCAGGATCTCCCGACTCCTTTCCATGCGTTCCGGCATCCCAGTGCGAC
GCCTGGGGAGCTCATGGGAGGCTAACGGCTTCGCCTGCGGTATCGTGGCCTGAGCCTTTG
TAGTGCAACGTTAATAGCTGTATTGGTGACTGTCCTTGTCCAATGAAGGCAGGAGCCCAG
CTCCTACGGGTAGTAAACATACTGTCACAACTATAGTGTTCGCATGGTGGATAGTACCCA
AATGCGTCCACAACAGTTATCAATCAA',
    ],
];

