#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;

# Prepare a transcriptome that has no genome so MOOP can display it: build a fake
# reference FASTA and a matching GFF3 from the transcript FASTA and the mapping
# files.
#
# Run make_t2g_from_fasta.pl FIRST -- it owns the rule that turns a sequence id
# into a gene id, and that rule must exist in exactly one place:
#
#   perl scripts/make_t2g_from_fasta.pl --transcript transcript.nt.fa \
#                                       --protein   protein.aa.fa
#   perl scripts/make_fake_genome_from_t2g.pl --t2g transcript2gene.txt \
#                                       --transcript-fasta transcript.nt.fa
#
# LAYOUT: ONE REFERENCE SEQUENCE PER GENE, CARRYING ITS LONGEST ISOFORM.
#
# Chosen deliberately (user, 2026-07-28) over one-ref-per-transcript, which cannot
# express a gene at all -- that is why Bipalium_kewense, built that way, has 39,065
# mRNA rows and ZERO gene rows. Keeping the gene means isoforms share its reference.
#
# ⚠️  THE KNOWN COST, and it is real: the reference holds only the LONGEST isoform,
# so a shorter isoform's coordinates do not correspond to its own bases. In a
# genome browser a shorter isoform is drawn against the longest one's sequence.
# Identifiers, parentage and lengths are all correct; only the underlying bases of
# the shorter isoforms are not theirs. This script counts those and says so, and
# writes the same warning into the GFF header, so the limitation travels with the
# file instead of living only in someone's memory.
#
# Nothing here renames anything. Identifiers are written exactly as the mapping
# files spell them -- MOOP's :pep/:cds naming is applied later, to MOOP's copies.
#
# Usage:
#   make_fake_genome_from_t2g.pl --t2g transcript2gene.txt
#                                --transcript-fasta transcript.nt.fa
#                                [--c2g cds2gene.txt] [--cds-fasta cds.nt.fa]
#                                [--genome-out genome.fa] [--gff-out genes.gff]
#                                [--ref-suffix .ref] [--source NAME]

my ($t2g, $c2g, $tx_fa, $cds_fa, $genome_out, $gff_out, $ref_suffix, $source);
$genome_out = 'genome.fa';
$gff_out    = 'genes.gff';
$ref_suffix = '.ref';
$source     = 'moop_t2g';

GetOptions(
    't2g=s'              => \$t2g,
    'c2g=s'              => \$c2g,
    'transcript-fasta=s' => \$tx_fa,
    'cds-fasta=s'        => \$cds_fa,
    'genome-out=s'       => \$genome_out,
    'gff-out=s'          => \$gff_out,
    'ref-suffix=s'       => \$ref_suffix,
    'source=s'           => \$source,
) or die usage();

die usage() unless $t2g && $tx_fa;
die "Cannot read $t2g\n"   unless -s $t2g;
die "Cannot read $tx_fa\n" unless -s $tx_fa;

my %tx2gene  = read_map($t2g);
my %cds2gene = ($c2g && -s $c2g) ? read_map($c2g) : ();
my %tx_seq   = fasta_seqs($tx_fa);
my %cds_len  = ($cds_fa && -s $cds_fa) ? fasta_lengths($cds_fa) : ();

# Gene -> transcripts, sorted so output is byte-reproducible across runs.
my (%gene_tx, @gene_order);
foreach my $tx (sort keys %tx2gene) {
    my $gene = $tx2gene{$tx};
    push @gene_order, $gene unless exists $gene_tx{$gene};
    push @{ $gene_tx{$gene} }, $tx;
}

# A CDS/protein id belongs to a TRANSCRIPT but the mapping files record only its
# gene. Recover it exactly as parse_transcript2gene_to_MOOP_TSV.pl does: strip a
# trailing ".p<N>" ORF marker and keep it only if that names a real transcript.
my (%tx_cds, $unresolved_cds);
foreach my $cds_id (sort keys %cds2gene) {
    (my $base = $cds_id) =~ s/\.p\d+$//i;
    if (exists $tx2gene{$base}) { push @{ $tx_cds{$base} }, $cds_id }
    else                        { $unresolved_cds++ }
}

open my $gfa, '>', $genome_out or die "Cannot write $genome_out: $!\n";
open my $gff, '>', $gff_out    or die "Cannot write $gff_out: $!\n";

print $gff "##gff-version 3\n";
print $gff "# Generated by make_fake_genome_from_t2g.pl from $t2g + $tx_fa\n";
print $gff "# SYNTHETIC REFERENCE: this transcriptome has no genome. Each GENE is a\n";
print $gff "# reference sequence carrying its LONGEST isoform. Shorter isoforms are\n";
print $gff "# placed on that same sequence, so their coordinates do NOT correspond to\n";
print $gff "# their own bases. Ids, parentage and lengths are correct; the underlying\n";
print $gff "# sequence of a shorter isoform is not its own.\n";

my ($n_genes, $n_tx, $n_cds, $n_shorter, $missing_seq) = (0, 0, 0, 0, 0);

foreach my $gene (@gene_order) {
    my @txs = @{ $gene_tx{$gene} };

    # Longest isoform defines both the reference sequence and the gene span.
    my ($best_tx, $best_len) = (undef, -1);
    foreach my $tx (@txs) {
        my $seq = $tx_seq{$tx};
        if (!defined $seq) { $missing_seq++; next; }
        if (length($seq) > $best_len) { ($best_tx, $best_len) = ($tx, length $seq); }
    }
    next unless defined $best_tx;      # no sequence for any isoform: skip the gene

    my $seqid = $gene . $ref_suffix;
    print $gfa ">$seqid ORG_TRANSCRIPT=$best_tx\n";
    my $seq = $tx_seq{$best_tx};
    for (my $pos = 0; $pos < length($seq); $pos += 60) {
        print $gfa substr($seq, $pos, 60), "\n";
    }
    $n_genes++;

    print $gff join("\t", $seqid, $source, 'gene', 1, $best_len, '.', '+', '.',
                    "ID=$gene;Name=$gene"), "\n";

    foreach my $tx (@txs) {
        my $seq_tx = $tx_seq{$tx};
        next unless defined $seq_tx;
        my $len = length $seq_tx;
        $n_shorter++ if $len < $best_len;
        $len = $best_len if $len > $best_len;   # cannot exceed the reference
        $n_tx++;

        print $gff join("\t", $seqid, $source, 'transcript', 1, $len, '.', '+', '.',
                        "ID=$tx;Parent=$gene"), "\n";
        print $gff join("\t", $seqid, $source, 'exon', 1, $len, '.', '+', '.',
                        "Parent=$tx"), "\n";

        foreach my $cds_id (@{ $tx_cds{$tx} || [] }) {
            my $clen = $cds_len{$cds_id} || $len;
            $clen = $len if $clen > $len;
            print $gff join("\t", $seqid, $source, 'CDS', 1, $clen, '.', '+', '0',
                            "ID=$cds_id;Parent=$tx"), "\n";
            $n_cds++;
        }
    }
}
close $gfa or die "Cannot close $genome_out: $!\n";
close $gff or die "Cannot close $gff_out: $!\n";

printf "Written: %s (%d reference sequences, one per gene)\n", $genome_out, $n_genes;
printf "Written: %s (%d gene, %d transcript, %d CDS)\n", $gff_out, $n_genes, $n_tx, $n_cds;

if ($n_shorter) {
    printf STDERR "\n!! %d of %d transcript(s) are SHORTER than their gene's reference\n"
                . "!! sequence, which carries the longest isoform only. Their ids,\n"
                . "!! parentage and lengths are right; the bases under them are the\n"
                . "!! longest isoform's, not their own. This is inherent to one\n"
                . "!! reference per gene and is recorded in the GFF header.\n\n",
        $n_shorter, $n_tx;
}
warn "NOTE: $missing_seq transcript(s) in $t2g had no sequence in $tx_fa\n" if $missing_seq;
warn "NOTE: $unresolved_cds CDS id(s) did not reduce to a known transcript\n"  if $unresolved_cds;

sub read_map {
    my ($file) = @_;
    my %map;
    open my $in, '<', $file or die "Cannot open $file: $!\n";
    while (my $line = <$in>) {
        chomp $line;
        next if $line =~ /^\s*#/ || $line !~ /\S/;
        my ($id, $gene) = split /\t/, $line;
        next unless defined $id && defined $gene && $id ne '' && $gene ne '';
        $map{$id} = $gene;
    }
    close $in;
    die "No usable rows in $file\n" unless %map;
    return %map;
}

sub fasta_seqs {
    my ($file) = @_;
    my (%seq, $id);
    open my $in, '<', $file or die "Cannot open $file: $!\n";
    while (my $line = <$in>) {
        chomp $line;
        if ($line =~ /^>(\S+)/) { $id = $1; $seq{$id} = ''; next; }
        next unless defined $id;
        $line =~ s/\s+//g;
        $seq{$id} .= $line;
    }
    close $in;
    return %seq;
}

sub fasta_lengths {
    my ($file) = @_;
    my %seq = fasta_seqs($file);
    my %len;
    foreach my $id (keys %seq) { $len{$id} = length $seq{$id}; }
    return %len;
}

sub usage {
    return <<"USAGE";
Usage: $0 --t2g transcript2gene.txt --transcript-fasta transcript.nt.fa
          [--c2g cds2gene.txt] [--cds-fasta cds.nt.fa]
          [--genome-out genome.fa] [--gff-out genes.gff]
          [--ref-suffix .ref] [--source NAME]

Builds a synthetic reference FASTA and GFF3 for a transcriptome with no genome.
One reference sequence per GENE, carrying its longest isoform. Run
make_t2g_from_fasta.pl first to produce the mapping files.
USAGE
}
