/**
 * Centralized Help Text
 * Used across all search pages (organism, assembly, groups, multi-organism)
 */

const SEARCH_HELP = {
    // Basic search help (used on organism and assembly pages)
    basic: `<strong>How to Search</strong><br><br><strong>Single Word Searches:</strong><br>Enter a single keyword to find all matching annotations. Example: "kinase"<br><br><strong>Multi-Word Searches:</strong><br>Enter multiple words separated by spaces to find records containing ALL of the terms. The terms can appear anywhere in the text. Example: "kinase domain" finds records that contain BOTH kinase AND domain<br><br><strong>Exact Phrase Searches:</strong><br>Use quotes to search for exact phrases. Example: "ABC transporter" finds only exact matches<br><br><strong>Minimum Character Requirement:</strong><br>Terms with fewer than 3 characters are automatically ignored. Example: searching for "P53 tumor" will only search for "tumor" since "P53" has fewer than 3 characters<br><br><strong>Search Types:</strong><br>• <strong>Gene IDs:</strong> Search by gene name, UniProt ID, or other identifiers<br>• <strong>Annotations:</strong> Search across all annotation types<br><br><strong>Results Limit:</strong><br>Results are capped at 2,500 - use more specific terms to refine your search<br><br><strong>Filtering:</strong><br>Click the filter button to limit search to specific annotation sources`,

    // Group-specific search help
    group: `<strong>How to Search</strong><br><br><strong>Single Word Searches:</strong><br>Enter a single keyword to find all matching annotations. Example: "kinase"<br><br><strong>Multi-Word Searches:</strong><br>Enter multiple words separated by spaces to find records containing ALL of the terms. The terms can appear anywhere in the text. Example: "kinase domain" finds records that contain BOTH kinase AND domain<br><br><strong>Exact Phrase Searches:</strong><br>Use quotes to search for exact phrases. Example: "ABC transporter" finds only exact matches<br><br><strong>Minimum Character Requirement:</strong><br>Terms with fewer than 3 characters are automatically ignored. Example: searching for "P53 tumor" will only search for "tumor" since "P53" has fewer than 3 characters<br><br><strong>Search Types:</strong><br>• <strong>Gene IDs:</strong> Search by gene name, UniProt ID, or other identifiers<br>• <strong>Annotations:</strong> Search across all annotation types<br><br><strong>Select Organisms:</strong><br>Use the checkboxes in the "Organisms in Group" section below to select/deselect which organisms to include in your search<br><br><strong>Results Limit:</strong><br>Results are capped at 2,500 per organism - use more specific terms to refine your search<br><br><strong>Filtering:</strong><br>Click the filter button to limit search to specific annotation sources`,

    // Multi-organism search help
    multiOrganism: `<strong>How to Search</strong><br><br><strong>Single Word Searches:</strong><br>Enter a single keyword to find all matching annotations. Example: "kinase"<br><br><strong>Multi-Word Searches:</strong><br>Enter multiple words separated by spaces to find records containing ALL of the terms. The terms can appear anywhere in the text. Example: "kinase domain" finds records that contain BOTH kinase AND domain<br><br><strong>Exact Phrase Searches:</strong><br>Use quotes to search for exact phrases. Example: "ABC transporter" finds only exact matches<br><br><strong>Minimum Character Requirement:</strong><br>Terms with fewer than 3 characters are automatically ignored. Example: searching for "P53 tumor" will only search for "tumor" since "P53" has fewer than 3 characters<br><br><strong>Search Types:</strong><br>• <strong>Gene IDs:</strong> Search by gene name, UniProt ID, or other identifiers<br>• <strong>Annotations:</strong> Search across all annotation types<br><br><strong>Select Organisms:</strong><br>Use the checkboxes in the "Selected Organisms" section below to select/deselect which organisms to include in your search<br><br><strong>Results Limit:</strong><br>Results are capped at 2,500 per organism - use more specific terms to refine your search<br><br><strong>Filtering:</strong><br>Click the filter button to limit search to specific annotation sources`,

    // Results help (same for all pages)
    results: `<strong>Using Your Results</strong><br><br><strong>Filter Results:</strong><br>Use the search boxes above each column header to filter results. Type to narrow down results by specific values.<br><br><strong>Sort Results:</strong><br>Click any column header to sort ascending or descending. Click again to reverse the sort order.<br><br><strong>Select and Export:</strong><br>Use the checkboxes to select specific rows, then click export buttons at the bottom:<br>• <strong>Copy:</strong> Copy selected rows to clipboard<br>• <strong>CSV:</strong> Download as comma-separated values file<br>• <strong>Excel:</strong> Download as Excel spreadsheet<br>• <strong>PDF:</strong> Download as PDF document<br>• <strong>Print:</strong> Print selected results<br><br><strong>Column Visibility:</strong><br>Click the "Column Visibility" button to show or hide specific columns based on your needs.<br><br><strong>View Details:</strong><br>Click on any gene or annotation link to view detailed information on the gene/parent feature page.`
};
